spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Othmane-2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        ejb:
          interceptor: com.example.stockspring.interceptor.interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    logging:
      level:
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8080

flickr:
  apiKey: 9c258d56f13054168d46343e42f4137c
  apiSecret: 173c253b0ff88009
  appKey: 72157720902092876-4355760a4a4be4f2
  appSecret: af408a804cf419bd
